version: "3.9"

services:
  db:
    image: postgres:17
    container_name: db-challenge-mottu
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-SenhaMuitoForte1234!}
      POSTGRES_DB: ${DB_NAME:-challengemottu_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-challengemottu_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-challenge-mottu
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ASPNETCORE_URLS: http://+:8080
      DOTNET_ENVIRONMENT: Development
      DOTNET_RUNNING_IN_CONTAINER: "true"
      Jwt__Key: ${JWT_KEY:-uqW8EXYt+3WOsDntgbG5Jt68rNTMmKZwpawNRcMIkSY=}
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${DB_NAME:-challengemottu_db};Username=${DB_USER:-postgres};Password=${DB_PASS:-SenhaMuitoForte1234!}"
      Mqtt__Host: host.docker.internal
      Mqtt__Port: 1883
    ports:
      - "8080:8080"

volumes:
  pgdata:
